class Team:
    first_row_name_user = "(//*[@data-test-id='table-body']//td[contains(@class, 'styles_tableUser')])[1]"
    second_row_name_user = "(//tr[contains(@class, 'hover-visible-container')])[2]//td[contains(@class, 'styles_tableUser')]"
    first_row_status = "(//tr[contains(@class, 'hover-visible-container')])[1]//td[contains(@class, 'styles_tableStatus')]"
    first_row_role = "(//tr[contains(@class, 'hover-visible-container')])[1]//td[contains(@class, 'styles_tableRole')]"
    first_row_limit = "(//tr[contains(@class, 'hover-visible-container')])[1]//td[contains(@class, 'styles_tableLimit')]"
    first_row_declined_rate = "(//tr[contains(@class, 'hover-visible-container')])[1]//td[contains(@class, 'styles_tableDeclineRate')]"
    first_row_spend = "(//tr[contains(@class, 'hover-visible-container')])[1]//td[contains(@class, 'styles_tableSpend')]"
    modal_name_user = "//*[@data-test-id = 'modal-dialog']//*[contains(@class, 'styles_containerBodyL')]"
    modal_email_user = "(//*[@data-test-id = 'modal-dialog']//*[contains(@class, 'display_flex flex-direction_column gap_1 flex_1 min-width_0')]//span)[2]"
    modal_role_user = "(//*[@data-test-id = 'modal-dialog']//*[contains(@class, 'styles_containerRegular')])[2]"
    modal_limit = "(//*[@data-test-id = 'limit-info'])[2]"
    pencil_button = "//div[contains(@class, 'display_flex align-items_center')]/button"
    title_change_limit = "(//div[@data-test-id = 'modal-dialog']//h2)[2]"
    button_send_invite_ru = "//button//span[contains(text(), 'Отправить приглашение')]"
    limit_card = '//*[@data-test-id="select"]//*[@data-slot="icon"]'
    limit_daily = "//button[@data-test-id = 'action']//div[contains(text(), 'Daily')]"
    limit_daily_ru = "//button[@data-test-id = 'action']//div[contains(text(), 'День')]"
    limit_monthly_ru = "//button[@data-test-id = 'action']//div[contains(text(), 'Месяц')]"
    limit_no_limit = "//button[@data-test-id = 'action']//div[contains(text(), 'No limit')]"
    input_limit_amount = "//input[@id = 'limit_amount']"
    menu_button = "//div[@data-test-id = 'modal-header']//*[@data-test-id='button'][1]"
    button_change_role_ru = "//div[contains(text(), 'Изменить роль')]"
    admin_role = "(//*[@data-test-id = 'radio-button'])[1]"
    emploe_role = "(//*[@data-test-id = 'radio-button'])[2]/div[2]"
    button_save_ru = "//button//span[contains(text(), 'Сохранить')]"
    filter_by_status_ru = "//button//span[contains(text(),'Статус')]"
    status_active = "(//*[@data-test-id='checkbox'])[1]"
    status_delete = "(//*[@data-test-id='checkbox'])[3]"
    clear_filters_ru = "//span[contains(text(), 'Очистить фильтры')]"
    filter_visible = "//div[@data-test-id = 'tag']"
    button_invite = "//button[@data-test-id = 'modal-activator']"
    input_email = '//*[@data-test-id="text-field"]//input[@id="email"]'
    delete_invite = "(//button[@data-test-id ='action'])[1]"
    button_delete = "(//div[@data-test-id = 'modal-footer']//button[@data-test-id ='button'])[2]"
    notification_send_letter = "//div[@data-test-id = 'toast']"
    title_table_user = "//th[contains(@class, 'styles_tableUser')]"
    title_table_status = "//th[contains(@class, 'styles_tableStatus')]"
    title_table_role = "//th[contains(@class, 'styles_tableRole')]"
    title_table_limit = "//th[contains(@class, 'styles_tableLimit')]"
    title_table_spend = "//th[contains(@class, 'styles_tableSpend')]"
    title_table_decline_rate = "(//th[contains(@class, 'styles_tableDeclineRate')])[1]"
    first_new_sort_ru = "//span[contains(text(), 'Сначала новые')]"
    first_old_sort_ru = "//span[contains(text(), 'Сначала старые')]"
    ascending_sort_ru = "//span[contains(text(), 'По возрастанию')]"
    descending_sort_ru = "//span[contains(text(), 'По убыванию')]"
    table_pagination = '//*[@data-test-id="table-pagination"]'
    btn_cancel_ru = '//*[@data-test-id="button"]//span[contains(text(), "Отменить")]'
    btn_send_ru = '//*[@data-test-id="button"]//span[contains(text(), "Отправить приглашение")]'

