from time import sleep

import allure
import pytest

from playwright.sync_api import Page, expect

from data.input_data.random_data import random_string
from data.input_data.users import USER_UK, USER_RU, USER_EN, USER_NOT_ACTIVATED_COMPANY, USER_NOT_ACTIVATED_COMPANY_EN, \
    USER_NOT_ACTIVATED_COMPANY_UK
from pages.pages import Pages

from steps import Steps
from utils.consts import ONBOARDING_URL, AUTH_URL

telegram = '@' + random_string(8)
first_name = random_string(10)
last_name = random_string(4)
email = last_name + '@gmail.com'
password = random_string(9)
first_name_1 = random_string(22)
company_name = random_string(6)

#TODO:переписать класс
class TestOnboarding:

    @allure.title('Создание соло en')
    @pytest.mark.conf(locale="en-GB")
    def test_solo_onboarding_create_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_facebook()
        steps.onboarding.click_next()
        steps.onboarding.check_title_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_btn_over_100000()
        steps.onboarding.click_next()
        steps.onboarding.check_title_solo_or_team_en()
        steps.onboarding.check_btn_disabled(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.click_next()
        steps.onboarding.check_title_create_company()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.check_text_agree_en()
        steps.onboarding.click_company_create()
        steps.onboarding.title_check_email_en()
        steps.onboarding.title_check_email_address_en()

    @allure.title('Создание соло ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_solo_onboarding_create_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_facebook()
        steps.onboarding.click_google()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_solo_or_team_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.button_create_company_ru()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.click_button_create_company_ru()
        steps.onboarding.check_title_solo_or_team_en()
        steps.onboarding.title_check_email_ru()
        steps.onboarding.title_check_email_address_ru()
        page.get_by_placeholder("Введите пароль для подтверждения").is_visible()
        steps.onboarding.btn_code_confirm_ru()

    @allure.title('Создание соло uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_test_solo_onboarding_create_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.click_facebook()
        steps.onboarding.click_google()
        steps.onboarding.click_taboola()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.money_spend_30_50_box.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_solo_or_team_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.slider_visible()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_create_company_uk()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.check_text_agree_uk()
        steps.onboarding.click_btn_confirm_create_uk()
        steps.onboarding.title_check_email_uk()
        steps.onboarding.btn_code_confirm_uk()

    @allure.title('Создание team en')
    @pytest.mark.conf(locale="en-GB")
    def test_team_onboarding_create_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_first_page_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_google()
        steps.onboarding.click_next()
        steps.onboarding.check_title_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_btn_50_100_en()
        steps.onboarding.click_next()
        steps.onboarding.check_title_solo_or_team_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_button_team_en()
        steps.onboarding.slider_visible()
        steps.onboarding.click_next()
        sleep(3)
        steps.onboarding.check_title_create_company()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.click_company_create()
        steps.onboarding.title_check_email_en()
        steps.onboarding.title_check_email_address_en()
        sleep(3)
        steps.onboarding.button_code_en()

    @allure.title('Создание team uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_team_onboarding_create_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_first_page_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.click_facebook()
        steps.onboarding.click_google()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.check_title_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.money_spend_check_box_uk.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_solo_or_team_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.checkbox_team_uk.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.check_title_create_company_uk()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.click_btn_confirm_create_uk()
        sleep(3)
        steps.onboarding.title_check_email_uk()
        steps.onboarding.btn_code_confirm_uk()

    @allure.title('Создание team ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_team_onboarding_create_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_google()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.click_btn_more_100_ru()
        steps.onboarding.click_btn_next_ru()
        pages.onboard.checkbox_team_uk.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.click_button_create_company_ru()
        sleep(2)
        page.get_by_text("Ввести код подтверждения").is_visible()

    @allure.title('Создание lead solo en')
    @pytest.mark.conf(locale="en-GB")
    def test_solo_onboarding_wait_list_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.check_first_page_en()
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_taboola()
        steps.onboarding.click_next()
        steps.onboarding.check_title_en()
        steps.onboarding.check_btn_disabled(page)
        pages.onboard.money_spend_under_10k_box_en.click()
        steps.onboarding.click_next()
        steps.onboarding.check_title_solo_or_team_en()
        steps.onboarding.check_btn_disabled(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.slider_visible()
        steps.onboarding.click_next()
        steps.onboarding.title_lead_en()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_en()
        sleep(5)
        expect(page.locator('//h1')).to_have_text("You're now on our waitlist!")
        page.locator("//p[contains(text(), '© 2024 dev host')]").scroll_into_view_if_needed()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.check_text_in_wait_list_en()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your personal manager')]")).to_be_visible()
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Let's talk")

    @allure.title('Создание lead solo ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_solo_onboarding_wait_list_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_microsoft()
        steps.onboarding.click_another()
        steps.onboarding.click_taboola()
        steps.onboarding.check_first_page_ru()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_solo_or_team_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.title_lead_ru()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_ru()
        sleep(3)
        expect(page.locator('//h1')).to_have_text('Вы добавлены в лист ожидания!')
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Связаться")
        steps.onboarding.check_text_in_wait_list_ru()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Персональный менеджер')]")).to_be_visible()

    @allure.title('Создание lead solo uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_solo_onboarding_wait_list_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_microsoft()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        page.get_by_text('Менше $10,000').click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_solo_or_team_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.title_lead_uk()
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_uk()
        sleep(3)
        expect(page.locator('//h1')).to_have_text('Ви тепер у нашому списку очікування!')
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Зв'язатися")
        steps.onboarding.check_text_in_wait_list_uk()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Особистий менеджер')]")).to_be_visible()

    @allure.title('Создание lead team en')
    @pytest.mark.conf(locale="en-GB")
    def test_team_onboarding_wait_list_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_first_page_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_microsoft()
        steps.onboarding.click_taboola()
        steps.onboarding.click_next()
        steps.onboarding.check_title_en()
        steps.onboarding.check_btn_disabled(page)
        pages.onboard.money_spend_under_10k_box_en.click()
        steps.onboarding.click_next()
        steps.onboarding.check_title_solo_or_team_en()
        steps.onboarding.check_btn_disabled(page)
        steps.onboarding.click_button_team_en()
        steps.onboarding.click_next()
        steps.onboarding.title_lead_en()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_en()
        steps.onboarding.title_check_email_en()
        steps.onboarding.title_check_email_address_en()
        steps.onboarding.btn_code_confirm_en()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your personal manager')]")).to_be_visible()
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Let's talk")

    @allure.title('Создание lead team ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_team_onboarding_wait_list_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_microsoft()
        steps.onboarding.click_another()
        steps.onboarding.click_taboola()
        steps.onboarding.check_first_page_ru()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.check_title_solo_or_team_ru()
        steps.onboarding.check_btn_disabled_ru(page)
        pages.onboard.button_team_ru.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.title_lead_ru()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_ru()
        steps.onboarding.title_check_email_ru()
        steps.onboarding.title_check_email_address_ru()
        steps.onboarding.btn_code_confirm_ru()
        expect(page.locator('//h1')).to_have_text('Вы добавлены в лист ожидания!')
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Связаться")
        steps.onboarding.check_text_in_wait_list_ru()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Персональный менеджер')]")).to_be_visible()

    @allure.title('Создание lead team uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_team_onboarding_wait_list_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.check_first_page_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        steps.onboarding.click_tik_tok()
        steps.onboarding.click_taboola()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        page.get_by_text('Менше $10,000').click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.check_title_solo_or_team_uk()
        steps.onboarding.check_btn_disabled_uk(page)
        pages.onboard.checkbox_team_uk.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.click_create_lead_uk()
        steps.onboarding.check_title_leave_lead_uk()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.click_create_lead_uk()
        steps.onboarding.title_check_email_uk()
        steps.onboarding.title_check_email_address_uk()
        steps.onboarding.btn_code_confirm_uk()
        steps.onboarding.check_text_in_wait_list_uk()
        expect(page.locator("//*[@data-test-id='button']//span")).to_have_text("Зв'язатися")
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Особистий менеджер')]")).to_be_visible()

    @allure.title('Check page design en')
    @pytest.mark.conf(locale="en-GB")
    def test_check_page_design_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        page.get_by_text("Have an account?").is_visible()
        page.get_by_alt_text("dev host logo").is_visible()
        steps.onboarding.policy_visible_en()
        steps.onboarding.terms_of_use_visible_en()
        expect(page.get_by_text("© 2024 dev host")).to_be_visible()
        steps.onboarding.check_btn_login_en()
        steps.onboarding.click_taboola()
        steps.onboarding.click_next()
        steps.onboarding.slider_visible()
        page.get_by_text("Have an account?").is_visible()
        page.get_by_alt_text("dev host logo").is_visible()
        steps.onboarding.policy_visible_en()
        steps.onboarding.terms_of_use_visible_en()
        expect(page.get_by_text("© 2024 dev host")).to_be_visible()
        steps.onboarding.check_btn_login_en()
        steps.onboarding.click_btn_50_100_en()
        steps.onboarding.slider_visible()
        page.get_by_text("Have an account?").is_visible()
        page.get_by_alt_text("dev host logo").is_visible()
        steps.onboarding.policy_visible_en()
        steps.onboarding.terms_of_use_visible_en()
        expect(page.get_by_text("© 2024 dev host")).to_be_visible()
        steps.onboarding.check_btn_login_en()
        steps.onboarding.click_next()
        steps.onboarding.click_button_team_en()
        steps.onboarding.click_next()
        steps.onboarding.slider_visible()
        assert page.get_by_text("Have an account?").is_visible()
        page.get_by_alt_text("dev host logo").is_visible()
        steps.onboarding.policy_visible_en()
        steps.onboarding.terms_of_use_visible_en()
        expect(page.get_by_text("© 2024 dev host")).to_be_visible()
        steps.onboarding.check_btn_login_en()

    @allure.title('Check page design ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_check_page_design_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        page.locator("//p[contains(text(), 'Уже есть аккаунт?')]").wait_for(timeout=3000)
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.policy_visible_ru()
        steps.onboarding.terms_of_use_visible_ru()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.check_btn_login_ru()
        steps.onboarding.click_taboola()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.slider_visible()
        assert page.get_by_text("Уже есть аккаунт?").is_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.policy_visible_ru()
        steps.onboarding.terms_of_use_visible_ru()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.check_btn_login_ru()
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.slider_visible()
        assert page.get_by_text("Уже есть аккаунт?").is_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.policy_visible_ru()
        steps.onboarding.terms_of_use_visible_ru()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.check_btn_login_ru()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.slider_visible()
        assert page.get_by_text("Уже есть аккаунт?").is_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.policy_visible_ru()
        steps.onboarding.terms_of_use_visible_ru()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        steps.onboarding.check_btn_login_ru()

    @allure.title('Check page design uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_check_page_design_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        expect(page.get_by_text("У вас є рахунок?")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text("Політика конфіденційності")).to_be_visible()
        expect(page.get_by_text("Умови використання")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text('Логін')).to_be_visible()
        steps.onboarding.click_taboola()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.slider_visible()
        expect(page.get_by_text("У вас є рахунок?")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text("Політика конфіденційності")).to_be_visible()
        expect(page.get_by_text("Умови використання")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text('Логін')).to_be_visible()
        page.get_by_text('Менше $10,000').click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.slider_visible()
        expect(page.get_by_text("У вас є рахунок?")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text("Політика конфіденційності")).to_be_visible()
        expect(page.get_by_text("Умови використання")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text('Логін')).to_be_visible()
        pages.onboard.btn_solo.click()
        steps.onboarding.slider_visible()
        expect(page.get_by_text("У вас є рахунок?")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text("Політика конфіденційності")).to_be_visible()
        expect(page.get_by_text("Умови використання")).to_be_visible()
        expect(page.locator("//p[contains(text(), '© 2024 dev host')]")).to_be_visible()
        expect(page.get_by_text('Логін')).to_be_visible()

    @allure.title('Login from page onboarding en')
    @pytest.mark.conf(locale="en-GB")
    def test_login_from_onboarding(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        page.get_by_text('Login').click()
        expect(page.locator('//span[contains(text(), "Request invite")]')).to_be_visible()
        expect(page.locator("//h1[contains(text(), 'Welcome to dev host')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Forgot your password?')]")).to_be_visible()
        steps.onboarding.fill_email_login(USER_EN.login)
        steps.onboarding.fill_password(USER_EN.password)
        steps.onboarding.click_btn_enter_login_en()
        expect(page.locator('//h1')).to_have_text("Cash")

    @allure.title('Login from page onboarding ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_login_from_onboarding_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        steps.onboarding.check_btn_login_ru()
        steps.onboarding.click_btn_login_ru()
        expect(page.locator("//p[contains(text(), 'У вас нет аккаунта?')]")).to_be_visible()
        steps.auth.check_title()
        expect(page.get_by_text("Забыли пароль?")).to_be_visible()
        steps.auth.authorize(USER_RU)
        expect(page.locator('//h1')).to_have_text("Счет")

    @allure.title('Login from page onboarding uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_login_from_onboarding_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.slider_visible()
        page.get_by_text('Логін').click()
        page.get_by_text("У вас немає акаунту?").is_visible()
        page.get_by_text("Отримати запрошення").is_visible()
        page.get_by_text("Ласкаво просимо до dev host").is_visible()
        page.get_by_text("Авторизуйтесь, щоб продовжити").is_visible()
        page.get_by_text("Забули пароль?").is_visible()
        steps.onboarding.fill_email_login(USER_UK.login)
        steps.onboarding.fill_password(USER_UK.password)
        steps.onboarding.click_btn_enter_login_uk()
        page.locator('//h1').wait_for(timeout=3000)
        expect(page.locator('//h1')).to_have_text("Картки")

    @allure.title('Check errors team create en')
    @pytest.mark.conf(locale="en-GB")
    def test_check_errors_team_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_next()
        steps.onboarding.click_btn_over_100000()
        steps.onboarding.click_next()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_next()
        steps.onboarding.fill_first_name(first_name_1)
        steps.onboarding.click_company_create()
        page.get_by_text("Can be max 20 characters long").is_visible()
        page.get_by_text("Invalid email address").is_visible()
        page.get_by_text("Invalid Telegram nickname").is_visible()
        page.get_by_text("Should be at least 8 characters long").is_visible()

    @allure.title('Check errors solo create en')
    @pytest.mark.conf(locale="en-GB")
    def test_check_errors_solo_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_taboola()
        steps.onboarding.click_next()
        steps.onboarding.click_btn_50_100_en()
        steps.onboarding.click_next()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_next()
        steps.onboarding.fill_first_name(first_name_1)
        steps.onboarding.click_create_lead_en()
        page.get_by_text("Can be max 20 characters long").is_visible()
        page.get_by_text("Please complete this field").is_visible()
        page.get_by_text("Invalid email address").is_visible()
        page.get_by_text("Invalid Telegram nickname").is_visible()

    @allure.title('Check errors team create ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_check_errors_team_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.fill_last_name(first_name_1)
        steps.onboarding.click_button_create_company_ru()
        page.get_by_text("20 символов максимум").is_visible()
        page.get_by_text("Неверный email адрес").is_visible()
        page.get_by_text("Неверный Telegram-никнейм").is_visible()
        page.get_by_text("Должно быть не менее 8 символов").is_visible()

    @allure.title('Check errors solo create ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_check_errors_solo_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_another()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.click_btn_50_100()
        steps.onboarding.click_btn_next_ru()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.fill_last_name(first_name_1)
        steps.onboarding.click_create_lead_ru()
        page.get_by_text("20 символов максимум").is_visible()
        page.get_by_text("Неверный email адрес").is_visible()
        page.get_by_text("Неверный Telegram-никнейм").is_visible()

    @allure.title('Check errors team create uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_check_errors_team_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_btn_next_uk()
        page.get_by_text('Понад $100,000').click()
        steps.onboarding.click_btn_next_uk()
        pages.onboard.btn_solo.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.fill_last_name(first_name_1)
        steps.onboarding.click_btn_confirm_create_uk()
        page.get_by_text("20 символів максимум").is_visible()
        page.get_by_text("Невірна email адреса").is_visible()
        page.get_by_text("Невірний Telegram-нікнейм").is_visible()
        page.get_by_text("Має бути не менше 8 символів").is_visible()

    @allure.title('Check errors solo create uk')
    @pytest.mark.conf(locale="uk-UA")
    def test_check_error_first_name_solo_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_btn_next_uk()
        page.get_by_text('Менше $10,000').click()
        steps.onboarding.click_btn_next_uk()
        pages.onboard.checkbox_team_uk.click()
        steps.onboarding.click_btn_next_uk()
        steps.onboarding.fill_last_name(first_name_1)
        steps.onboarding.click_create_lead_uk()
        page.get_by_text("20 символів максимум").is_visible()
        page.get_by_text("Невірна email адреса").is_visible()
        page.get_by_text("Невірний Telegram-нікнейм").is_visible()

    @allure.title('Check error invalid code ru')
    @pytest.mark.conf(locale="ru-RU")
    def test_check_error_invalid_code_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(ONBOARDING_URL)
        steps.onboarding.click_facebook()
        steps.onboarding.click_google()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.click_btn_more_100_ru()
        steps.onboarding.click_btn_next_ru()
        pages.onboard.checkbox_team_uk.click()
        steps.onboarding.click_btn_next_ru()
        steps.onboarding.fill_company_name(company_name)
        steps.onboarding.fill_first_name(first_name)
        steps.onboarding.fill_last_name(last_name)
        steps.onboarding.fill_email(email)
        steps.onboarding.fill_telegram(telegram)
        steps.onboarding.fill_password(password)
        steps.onboarding.fill_password_confirm(password)
        steps.onboarding.click_button_create_company_ru()
        sleep(2)
        steps.onboarding.send_code_confirm("87654")
        page.get_by_text("Ввести код подтверждения").is_visible()
        page.locator('//*[@data-test-id="button"]//span[contains(text(), "Ввести код подтверждения")]').click()
        steps.onboarding.check_error_invalid_code()

    @allure.title('Check design page after onboarding')
    def test_design_page_after_onboarding_ru(self, page: Page, pages: Pages, steps: Steps):
        page.goto(AUTH_URL)
        pages.auth.login_input.fill(USER_NOT_ACTIVATED_COMPANY.login)
        pages.auth.password_input.fill(USER_NOT_ACTIVATED_COMPANY.password)
        pages.auth.login_button.click()
        expect(page.locator("(//span[contains(text(), 'do not activate')])[1]")).to_be_visible()
        expect(page.locator("(//span[contains(text(), 'do not activate')])[2]")).to_be_visible()
        expect(page.locator("//div[contains(text(), 'Счет')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Карты')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Транзакции')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Команда')]")).to_be_enabled()
        steps.universalSteps.check_second_title(page, 'Активируйте аккаунт')
        expect(page.locator("//h2/following-sibling::p")).to_have_text('В настоящее время мы работаем в приватном режиме и принимаем ограниченное количество команд. Свяжитесь с менеджером, чтобы получить приоритетную активацию, когда у нас появится возможность пригласить больше партнеров.')
        expect(page.locator("//span[contains(text(), '3% комиссии')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), '8 Бинов Visa и Mastercard')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Продвинутый функционал')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Персональный менеджер')]")).to_be_visible()
        expect(page.locator("//*[@data-test-id='button']//span[contains(text(), 'Связаться')]")).to_be_visible()

    @allure.title('Check design page after onboarding en')
    def test_design_page_after_onboarding_en(self, page: Page, pages: Pages, steps: Steps):
        page.goto(AUTH_URL)
        pages.auth.login_input.fill(USER_NOT_ACTIVATED_COMPANY_EN.login)
        pages.auth.password_input.fill(USER_NOT_ACTIVATED_COMPANY_EN.password)
        pages.auth.login_button.click()
        sleep(4)
        expect(page.locator("(//span[contains(text(), 'QGhzZwBXHj haSC')])[1]")).to_be_visible()
        expect(page.locator("(//span[contains(text(), 'QGhzZwBXHj haSC')])[2]")).to_be_visible()
        expect(page.locator("//div[contains(text(), 'Cash')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Cards')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Transactions')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Team')]")).to_be_enabled()
        steps.universalSteps.check_second_title(page, 'Activate your account')
        expect(page.locator("//h2/following-sibling::p")).to_have_text('We are currently operating in private mode and accepting a limited number of teams. Contact a manager to get priority activation when we have the opportunity to invite more partners.')
        expect(page.locator("//span[contains(text(), '3% commission')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), '8 Visa and Mastercard BINs')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Advanced functionality')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your personal manager')]")).to_be_visible()
        expect(page.locator("(//*[@data-test-id='button']//span)[2]")).to_have_text("Let's talk")

    @allure.title('Check design page after onboarding uk')
    def test_design_page_after_onboarding_uk(self, page: Page, pages: Pages, steps: Steps):
        page.goto(AUTH_URL)
        pages.auth.login_input.fill(USER_NOT_ACTIVATED_COMPANY_UK.login)
        pages.auth.password_input.fill(USER_NOT_ACTIVATED_COMPANY_UK.password)
        pages.auth.login_button.click()
        sleep(4)
        expect(page.locator("(//span[contains(text(), 'do not activate uk')])[1]")).to_be_visible()
        expect(page.locator("(//span[contains(text(), 'do not activate uk')])[2]")).to_be_visible()
        expect(page.locator("//div[contains(text(), 'Рахунок')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Картки')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Транзакції')]")).to_be_enabled()
        expect(page.locator("//span[contains(text(), 'Команда')]")).to_be_enabled()
        steps.universalSteps.check_second_title(page, 'Активуйте акаунт')
        expect(page.locator("//h2/following-sibling::p")).to_have_text(
            "Наразі ми працюємо в приватному режимі та приймаємо обмежену кількість команд. Зв'яжіться з менеджером, щоб отримати пріоритетну активацію, коли у нас з'явиться можливість запросити більше партнерів.")
        expect(page.locator("//span[contains(text(), '3% комісія')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), '8 BIN Visa та Mastercard')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Розширений функціонал')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Your Manager')]")).to_be_visible()
        expect(page.locator("//span[contains(text(), 'Особистий менеджер')]")).to_be_visible()
        expect(page.locator("(//*[@data-test-id='button']//span)[2]")).to_have_text("Зв'язатися")
