from pages.base_page import BasePage
from widgets.button import Button
from widgets.input import Input


class TeamPage(BasePage):
    def __init__(self) -> None:
        super().__init__()
        self.first_row_name_user = Button(selector=self._locators.team.first_row_name_user)
        self.first_row_status = Button(selector=self._locators.team.first_row_status)
        self.first_row_role = Button(selector=self._locators.team.first_row_role)
        self.first_row_limit = Button(selector=self._locators.team.first_row_limit)
        self.first_row_declined_rate = Button(selector=self._locators.team.first_row_declined_rate)
        self.first_row_spend = Button(selector=self._locators.team.first_row_spend)
        self.modal_name_user = Button(selector=self._locators.team.modal_name_user)
        self.modal_email_user = Button(selector=self._locators.team.modal_email_user)
        self.modal_role_user = Button(selector=self._locators.team.modal_role_user)
        self.modal_limit = Button(selector=self._locators.team.modal_limit)
        self.second_row_name_user = Button(selector=self._locators.team.second_row_name_user)
        self.button_send_invite_ru = Button(selector=self._locators.team.button_send_invite_ru)
        self.pencil_button = Button(selector=self._locators.team.pencil_button)
        self.title_change_limit = Button(selector=self._locators.team.title_change_limit)
        self.limit_card = Button(selector=self._locators.team.limit_card)
        self.input_limit_amount = Input(selector=self._locators.team.input_limit_amount)
        self.modal_save_limit_ru = Button(selector=self._locators.cards.modal_save_limit_ru)
        self.modal_save_limit_en = Button(selector=self._locators.cards.modal_save_limit_en)
        self.menu_button = Button(selector=self._locators.team.menu_button)
        self.change_card_limit_ru = Button(selector=self._locators.cards.change_card_limit_ru)
        self.change_card_limit_en = Button(selector=self._locators.cards.change_card_limit_en)
        self.button_change_role_ru = Button(selector=self._locators.team.button_change_role_ru)
        self.admin_role = Button(selector=self._locators.team.admin_role)
        self.emploe_role = Button(selector=self._locators.team.emploe_role)
        self.button_save_ru = Button(selector=self._locators.team.button_save_ru)
        self.filter_by_status_ru = Button(selector=self._locators.team.filter_by_status_ru)
        self.status_active = Button(selector=self._locators.team.status_active)
        self.status_delete = Button(selector=self._locators.team.status_delete)
        self.clear_filters_ru = Button(selector=self._locators.team.clear_filters_ru)
        self.filter_visible = Button(selector=self._locators.team.filter_visible)
        self.button_invite = Button(selector=self._locators.team.button_invite)
        self.input_email = Input(selector=self._locators.team.input_email)
        self.delete_invite = Button(selector=self._locators.team.delete_invite)
        self.button_delete = Button(selector=self._locators.team.button_delete)
        self.notification_send_letter = Button(selector=self._locators.team.notification_send_letter)
        self.title_table_user = Button(selector=self._locators.team.title_table_user)
        self.first_new_sort_ru = Button(selector=self._locators.team.first_new_sort_ru)
        self.first_old_sort_ru = Button(selector=self._locators.team.first_old_sort_ru)
        self.ascending_sort_ru = Button(selector=self._locators.team.ascending_sort_ru)
        self.descending_sort_ru = Button(selector=self._locators.team.descending_sort_ru)
        self.title_table_spend = Button(selector=self._locators.team.title_table_spend)
        self.title_table_decline_rate = Button(selector=self._locators.team.title_table_decline_rate)
        self.limit_daily = Button(selector=self._locators.team.limit_daily)
        self.limit_daily_ru = Button(selector=self._locators.team.limit_daily_ru)
        self.limit_monthly_ru = Button(selector=self._locators.team.limit_monthly_ru)
        self.limit_no_limit = Button(selector=self._locators.team.limit_no_limit)
        self.table_pagination = Button(selector=self._locators.team.table_pagination)
        self.btn_cancel_ru = Button(selector=self._locators.team.btn_cancel_ru)
        self.btn_send_ru = Button(selector=self._locators.team.btn_send_ru)
        self.title_table_status = Button(selector=self._locators.team.title_table_status)
        self.title_table_role = Button(selector=self._locators.team.title_table_role)
        self.title_table_limit = Button(selector=self._locators.team.title_table_limit)
