from pages.base_page import BasePage
from widgets.button import Button
from widgets.input import Input


class SettingsUserPage(BasePage):
    def __init__(self) -> None:
        super().__init__()
        self.main_avatar_empty = Button(selector=self._locators.settings_user.main_avatar_empty)
        self.profile_avatar_empty = Button(selector=self._locators.settings_user.profile_avatar_empty)
        self.button_show_password = Button(selector=self._locators.settings_user.button_show_password)
        self.input_name = Input(selector=self._locators.settings_user.input_name)
        self.input_last_name = Input(selector=self._locators.settings_user.input_last_name)
        self.button_update = Button(selector=self._locators.settings_user.button_update)
        self.toast_saved_changes = Button(selector=self._locators.settings_user.toast_saved_changes)
        self.span_name = Button(selector=self._locators.settings_user.span_name)
        self.title = Button(selector=self._locators.settings_user.title)
        self.add_file = Button(selector=self._locators.settings_user.add_file)
        self.button_save = Button(selector=self._locators.settings_user.button_save)
        self.select_timezone = Button(selector=self._locators.settings_user.select_timezone)
        self.title_change = Button(selector=self._locators.settings_user.title_change)
        self.button_add_file_ru = Button(selector=self._locators.settings_user.button_add_file_ru)
        self.size_files = Button(selector=self._locators.settings_user.size_files)
        self.tariff_name = Button(selector=self._locators.settings_user.tariff_name)
        self.sum_tariff = Button(selector=self._locators.settings_user.sum_tariff)
        self.status_active = Button(selector=self._locators.settings_user.status_active)
        self.description_tariff = Button(selector=self._locators.settings_user.description_tariff)
        self.limits_of_users_ru = Button(selector=self._locators.settings_user.limits_of_users_ru)
        self.title_tariff_plans_ru = Button(selector=self._locators.settings_user.title_tariff_plans_ru)
        self.title_tariff_plans = Button(selector=self._locators.settings_user.title_tariff_plans)
        self.basic_tariff = Button(selector=self._locators.settings_user.basic_tariff)
        self.sum_first_tariff = Button(selector=self._locators.settings_user.sum_first_tariff)
        self.sum_first_tariff_time = Button(selector=self._locators.settings_user.sum_first_tariff_time)
        self.description_first_tariff = Button(selector=self._locators.settings_user.description_first_tariff)
        self.info_in_modal = Button(selector=self._locators.settings_user.info_in_modal)
        self.basic_in_modal_card = Button(selector=self._locators.settings_user.basic_in_modal_card)
        self.credit_in_modal_card = Button(selector=self._locators.settings_user.credit_in_modal_card)
        self.prepaid_in_modal_card = Button(selector=self._locators.settings_user.prepaid_in_modal_card)
        self.number_card_basic_prepaid = Button(selector=self._locators.settings_user.number_card_basic_prepaid)
        self.private_in_modal_card = Button(selector=self._locators.settings_user.private_in_modal_card)
        self.international_in_modal_card = Button(selector=self._locators.settings_user.international_in_modal_card)
        self.number_card_international = Button(selector=self._locators.settings_user.number_card_international)
        self.title_security_page_ru = Button(selector=self._locators.settings_user.title_security_page_ru)
        self.change_password_ru = Button(selector=self._locators.settings_user.change_password_ru)
        self.title_modal_change_ru = Button(selector=self._locators.settings_user.title_modal_change_ru)
        self.input_old_password = Input(selector=self._locators.settings_user.input_old_password)
        self.input_new_password = Input(selector=self._locators.settings_user.input_new_password)
        self.input_confirm_password = Input(selector=self._locators.settings_user.input_confirm_password)
        self.title_password_ru = Button(selector=self._locators.settings_user.title_password_ru)
        self.title_session_ru = Button(selector=self._locators.settings_user.title_session_ru)
        self.title_active_session = Button(selector=self._locators.settings_user.title_active_session)
        self.this_session_ru = Button(selector=self._locators.settings_user.this_session_ru)
        self.language_session_ru = Button(selector=self._locators.settings_user.language_session_ru)
        self.title_referral_ru = Button(selector=self._locators.settings_user.title_referral_ru)
        self.button_reset_all_sessions_ru = Button(selector=self._locators.settings_user.button_reset_all_sessions_ru)
        self.button_reset_current_session_ru = Button(selector=self._locators.settings_user.button_reset_current_session_ru)
        self.user_session = Button(selector=self._locators.settings_user.user_session)
        self.current_session = Button(selector=self._locators.settings_user.current_session)
        self.theme = Button(selector=self._locators.settings_user.theme)
        self.theme_light = Button(selector=self._locators.settings_user.theme_light)
        self.english_in_modal = Button(selector=self._locators.settings_user.english_in_modal)
        self.russian_in_modal = Button(selector=self._locators.settings_user.russian_in_modal)
        self.ukr_in_modal = Button(selector=self._locators.settings_user.ukr_in_modal)
        self.english_in_row = Button(selector=self._locators.settings_user.english_in_row)
        self.russian_in_row = Button(selector=self._locators.settings_user.russian_in_row)
        self.ukr_in_row = Button(selector=self._locators.settings_user.ukr_in_row)
        self.language_edit = Button(selector=self._locators.settings_user.language_edit)
        self.title_modal_bin = Button(selector=self._locators.settings_user.title_modal_bin)
        self.type_modal_bin = Button(selector=self._locators.settings_user.type_modal_bin)
        self.number_bin_in_modal = Button(selector=self._locators.settings_user.number_bin_in_modal)
        self.img_network_modal_bin = Button(selector=self._locators.settings_user.img_network_modal_bin)
        self.input_code_2fa = Input(selector=self._locators.settings_user.input_code_2fa)

