from pages.base_page import BasePage
from widgets.button import Button


class CashBalancePage(BasePage):
    def __init__(self) -> None:
        super().__init__()

        self.accessible_balance_ru = Button(selector=self._locators.cash_balance.accessible_balance_ru)
        self.accessible_balance_sum = Button(selector=self._locators.cash_balance.accessible_balance_sum)
        self.balance_hold_ru = Button(selector=self._locators.cash_balance.balance_hold_ru)
        self.table_balance = Button(selector=self._locators.cash_balance.table_balance)
        self.icon_go_to_account = Button(selector=self._locators.cash_balance.icon_go_to_account)
        self.total_balance_ru = Button(selector=self._locators.cash_balance.total_balance_ru)
        self.balance_hold_sum = Button(selector=self._locators.cash_balance.balance_hold_sum)
        self.alert_title = Button(selector=self._locators.cash_balance.alert_title)
        self.alert_text = Button(selector=self._locators.cash_balance.alert_text)
        self.alert_title_with_trial = Button(selector=self._locators.cash_balance.alert_title_with_trial)
        self.alert_text_with_trial = Button(selector=self._locators.cash_balance.alert_text_with_trial)
        self.accessible_balance_account_ru = Button(selector=self._locators.cash_balance.accessible_balance_account_ru)
        self.balance_hold_account = Button(selector=self._locators.cash_balance.balance_hold_account)
        self.calendar_for_schedule = Button(selector=self._locators.cash_balance.calendar_for_schedule)
        self.button_back_to_cash = Button(selector=self._locators.cash_balance.button_back_to_cash)
        self.total_popover = Button(selector=self._locators.cash_balance.total_popover)
        self.total_popover_icon = Button(selector=self._locators.cash_balance.total_popover_icon)
        self.row_slider = Button(selector=self._locators.cash_balance.row_slider)
        self.balance_in_total_popover_ru = Button(selector=self._locators.cash_balance.balance_in_total_popover_ru)
        self.row_pending_transactions = Button(selector=self._locators.cash_balance.row_pending_transactions)
        self.total_sum_at_pending_trans_modal = Button(selector=self._locators.cash_balance.total_sum_at_pending_trans_modal)
        self.date_first_pending_at_modal = Button(selector=self._locators.cash_balance.date_first_pending_at_modal)
        self.sum_first_pending_at_modal = Button(selector=self._locators.cash_balance.sum_first_pending_at_modal)
        self.button_close_modal_pending = Button(selector=self._locators.cash_balance.button_close_modal_pending)
        self.beg_balance_popover_ru = Button(selector=self._locators.cash_balance.beg_balance_popover_ru)
        self.crypto_deposit_ru = Button(selector=self._locators.cash_balance.crypto_deposit_ru)
        self.money_in_popover_ru = Button(selector=self._locators.cash_balance.money_in_popover_ru)
        self.money_out_popover_ru = Button(selector=self._locators.cash_balance.money_out_popover_ru)
        self.crypto_fee_ru = Button(selector=self._locators.cash_balance.crypto_fee_ru)
        self.card_spend_ru = Button(selector=self._locators.cash_balance.card_spend_ru)
        self.settled_fee_ru = Button(selector=self._locators.cash_balance.settled_fee_ru)
        self.cross_border_fee_settled_ru = Button(selector=self._locators.cash_balance.cross_border_fee_settled_ru)
        self.decline_fee_ru = Button(selector=self._locators.cash_balance.decline_fee_ru)
        self.refund_ru = Button(selector=self._locators.cash_balance.refund_ru)
        self.refund_fee_ru = Button(selector=self._locators.cash_balance.refund_fee_ru)
        self.end_balance_ru = Button(selector=self._locators.cash_balance.end_balance_ru)
        self.filter_type_ru = Button(selector=self._locators.cash_balance.filter_type_ru)
        self.filter_deposit_ru = Button(selector=self._locators.cash_balance.filter_deposit_ru)
        self.filter_card_settled_ru = Button(selector=self._locators.cash_balance.filter_card_settled_ru)
        self.filter_card_declined_ru = Button(selector=self._locators.cash_balance.filter_card_declined_ru)
        self.filter_card_refund_ru = Button(selector=self._locators.cash_balance.filter_card_refund_ru)
        self.filter_deposit_fee_ru = Button(selector=self._locators.cash_balance.filter_deposit_fee_ru)
        self.user_at_modal = Button(selector=self._locators.cash_balance.user_at_modal)
        self.card_at_modal = Button(selector=self._locators.cash_balance.card_at_modal)
        self.popover_at_modal = Button(selector=self._locators.cash_balance.popover_at_modal)
        self.amount_at_modal = Button(selector=self._locators.cash_balance.amount_at_modal)
        self.status_at_modal = Button(selector=self._locators.cash_balance.status_at_modal)
        self.total_popover_icon_modal = Button(selector=self._locators.cash_balance.total_popover_icon_modal)
        self.card_spend_en = Button(selector=self._locators.cash_balance.card_spend_en)

