class methods:
    restMethods = [
	"/rest/access/userget",
	"/rest/access/useradd",
	"/rest/access/usermod",
	"/rest/access/userdel",
	"/rest/access/userenable",
	"/rest/access/groupget",
	"/rest/access/groupadd",
	"/rest/access/groupmod",
	"/rest/access/groupdel",
	"/rest/access/group_addusers",
	"/rest/access/group_delusers",
	"/rest/access/get_group_paths",
	"/rest/access/group_delpaths",
	"/rest/access/permsmod",
	"/rest/access/ldap_sync_ad",
	"/rest/account/is_logged_in",
	"/rest/account/login",
	"/rest/account/logout",
	"/rest/account/update_seal",
	"/rest/server/about",
	"/rest/server/license",
	"/rest/server/refresh_license",
	"/rest/server/locale",
	"/rest/graph/signals",
	"/rest/tree/node",
	"/rest/tree/nodes",
	# "/rest/server/is_app_installed",
	"/rest/alert/certain_alert",
	"/rest/alert/certain_alerts",
	# "/rest/account/read_web_custom",
	"/rest/account/del_web_custom",
	# "/rest/auth/v1/apps",
	# "/rest/auth/v1/apps",
	# "/rest/auth/v1/apps/{0}",
	# "/rest/auth/v1/apps/{0}",
	# "/rest/auth/v1/apps/{0}",
	# "/rest/auth/v1/apps/{0}/permissions",
	# "/rest/auth/v1/apps/{0}/permissions",
	# "/rest/auth/v1/apps/{0}/permissions/{1}",
	# "/rest/auth/v1/apps/{0}/permissions/{1}",
	# "/rest/auth/v1/apps/{0}/permissions/{1}",
	# "/rest/auth/v1/apps/{0}/roles",
	# "/rest/auth/v1/apps/{0}/roles",
	# "/rest/auth/v1/apps/{0}/roles/{1}",
	# "/rest/auth/v1/apps/{0}/roles/{1}",
	# "/rest/auth/v1/apps/{0}/roles/{1}",
	# "/rest/auth/v1/groups",
	# "/rest/auth/v1/apps/{0}/roles/{1}/groups",
	# "/rest/auth/v1/apps/{0}/roles/{1}/groups",
	# "/rest/auth/v1/apps/{0}/roles/{1}/groups/{2}",
	# "/rest/auth/v1/apps/{0}/roles/{1}/permissions",
	# "/rest/auth/v1/apps/{0}/roles/{1}/permissions",
	# "/rest/auth/v1/apps/{0}/roles/{1}/permissions/{2}",
	# "/rest/auth/v1/apps/{0}/roles/{1}/permissions/{2}",
	# "/rest/auth/v1/apps/{0}/roles/{1}/permissions/{2}",
	# "/rest/auth/v1/keys",
	# "/rest/auth/v1/keys",
	# "/rest/auth/v1/keys/{0}",
	# "/rest/auth/v1/keys/{0}",
	# "/rest/auth/v1/keys/{0}",
	# "/rest/auth/v1/public/certs",
	# "/rest/auth/v1/apps/{0}/authorize",
	# "/rest/auth/v1/apps/{0}/check-resource",
	# "/rest/auth/v1/actions/copy-permissions",
	# "/rest/auth/v1/actions/move-permissions",
	# "/rest/auth/v1/apps/{0}/authorize",
	"/rest/device/target",
	"/rest/device/target_views",
	"/rest/device/report_view",
	"/rest/device/targets",
	"/rest/alert/history",
	"/rest_long/alert/history",
	"/rest/alert/history",
	"/rest/alert/new_comment",
	"/rest_long/alert/comments",
	"/rest/inventory/targets",
    ]
